### ISSUE TITLE
Jenkins Slave restarting on ADOP creation

### ISSUE THREAD

**Issue by gogodi91** [Accenture/adop-docker-compose#31] opened 2016-04-05 11:46 UTC
I used the quickstart.sh script to create a new ADOP instance. I noticed that the Load_Platform job was hanging and on closer inspection I found that the jenkins slave is restarting. The docker logs had multiple lines of 

Error: Invalid or corrupt jarfile /bin/swarm-client.jar

**Comment by nickdgriffin** [comment] 2016-08-02 20:29
I believe this was initially caused by a new slave image having been built and the Swarm jar that we used had been moved however the image build hadn't failed.  #126 includes the new Slave version that's built with the new URL which shouldn't functionally change anything.

**Comment by SachinKSingh28** [comment] 2016-10-12 21:05
We should be able to close this as the slave container seems to come up cleanly without any issues.

**Comment by RobertNorthard** [comment] 2018-05-11 15:57
Closing as unable to repeat.

**Closed by RobertNorthard** 2018-05-11 15:57 UTC
