### ISSUE TITLE
Docker daemon not starting with quickstart.sh

### ISSUE THREAD

**Issue by rajivece** [Accenture/adop-docker-compose#190] opened 2017-02-20 04:37 UTC
Hi,
Im getting below error while running ADOP on aws with quickstart.sh 

```
./quickstart.sh -t aws -m sealabadop -c vpc-xxx -r us-east-1 -z a  -a xxxx -s xxxxx -u rajiv -p xxxxxx

      ###    ########   #######  ########
     ## ##   ##     ## ##     ## ##     ##
    ##   ##  ##     ## ##     ## ##     ##
   ##     ## ##     ## ##     ## ########
   ######### ##     ## ##     ## ##
   ##     ## ##     ## ##     ## ##
   ##     ## ########   #######  ##

Creating a new AWS variables file...
Running pre-create checks...
Creating machine...
(sealabadop) Launching instance...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with ubuntu(systemd)...
Installing Docker...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Checking connection to Docker...
Error creating machine: Error checking the host: Error checking and/or regenerating the certs: There was an error validating certificates for host "107.23.221.162:2376": read tcp 10.0.0.17:45111->107.23.221.162:2376: read: connection reset by peer
You can attempt to regenerate them using 'docker-machine regenerate-certs [name]'.
Be advised that this will trigger a Docker daemon restart which will stop running containers.
```

Here's is my docker-machine version

```
docker-machine version
docker-machine version 0.6.0, build e27fb87
```
I got below logs on docke-machine 

```
 journalctl -fu docker.service
-- Logs begin at Mon 2017-02-20 04:21:48 UTC. --
Feb 20 04:23:25 sealabadop systemd[1]: Stopping Docker Application Container Engine...
Feb 20 04:23:25 sealabadop dockerd[3927]: time="2017-02-20T04:23:25.948709206Z" level=info msg="Processing signal 'terminated'"
Feb 20 04:23:26 sealabadop dockerd[3927]: time="2017-02-20T04:23:26.025723719Z" level=info msg="stopping containerd after receiving terminated"
Feb 20 04:23:27 sealabadop systemd[1]: Stopped Docker Application Container Engine.
Feb 20 04:23:29 sealabadop systemd[1]: Started docker.service.
Feb 20 04:23:29 sealabadop docker[4639]: time="2017-02-20T04:23:29.094308614Z" level=info msg="libcontainerd: new containerd process, pid: 4649"
Feb 20 04:23:30 sealabadop docker[4639]: time="2017-02-20T04:23:30.128295561Z" level=fatal msg="Error starting daemon: error initializing graphdriver: driver not supported"
Feb 20 04:23:30 sealabadop systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Feb 20 04:23:30 sealabadop systemd[1]: docker.service: Unit entered failed state.
Feb 20 04:23:30 sealabadop systemd[1]: docker.service: Failed with result 'exit-code'.

```

I have started the quickstart.sh from ubuntu 10.04 LTS VM.
Kindly help me to resolve this issue.

**Comment by nickdgriffin** [comment] 2017-02-22 23:14
You'll need to upgrade Docker Machine as 0.6.0 is pretty old and we recommend 0.9.0 for evaluation mode: http://accenture.github.io/adop-docker-compose/docs/prerequisites/

It's caused by the fact that when Docker's install script tries to install AUFS it fails to find the package for the kernel version being used.

**Comment by rajivece** [comment] 2017-03-01 12:42
Nick,
Thanks for your suggestion. After upgrading the docker-machine to latest version ie. 0.9.0 I'm able to bring up the ADOPS successfully.

Now the Create Environment Job in Jenkins is failing with below message
jenkins/job/ExampleWorkspace/job/ExampleProject/job/Create_Environment/

Any suggestions, on this issue.
```
CI, tomcat.conf
TLS configuration is invalid - make sure your DOCKER_TLS_VERIFY and DOCKER_CERT_PATH are set correctly.
You might need to run `eval "$(docker-machine env default)"`
Build step 'Execute shell' marked build as failure
[ssh-agent] Stopped.
Warning: you have no plugins providing access control for builds, so falling back to legacy behavior of permitting any downstream builds to be triggered
Finished: FAILURE
```

**Comment by RobertNorthard** [comment] 2018-05-11 13:16
Resolving as answered by @nickdgriffin. @rajivece please let us know if you are still experiencing issues.

**Closed by RobertNorthard** 2018-05-11 13:16 UTC
